### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by unicornis-pl** [LiberatorUSA/GUCEF#1]
How to compile this package on Linux (Centos or Ubuntu)? Can you point me to the right direction?

I cannot fing configure script. When trying to regenerate it with autoconf, but I get the error message:
configure.ac:4: error: required file 'gucefMT/Makefile.in' not found
configure.ac:4: error: required file 'gucefMT/src/Makefile.in' not found

I tried cmake, but no luck as well:
- Configuring GUCEF 0.1.2
-- Detected g++ 4.8.3

-- Enabling GCC visibility flags
CMake Warning at projects/CMake/Dependencies.cmake:178 (find_package):
  By not providing "FindCppUnit.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CppUnit", but
  CMake did not find one.

  Could not find a package configuration file provided by "CppUnit" with any
  of the following names:

    CppUnitConfig.cmake
    cppunit-config.cmake

  Add the installation prefix of "CppUnit" to CMAKE_PREFIX_PATH or set
  "CppUnit_DIR" to a directory containing one of the above files.  If
  "CppUnit" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:99 (include)

CMake Warning (dev) at tools/CMakeLists.txt:16 (add_subdirectory):
  The source directory

    /home/jj/dsc/GUCEF-master/tools/PatcherGUI

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error at plugins/GUI/guidriverCEGUI/CMakeLists.txt:104 (add_library):
  Cannot find source file:

    src/guidriverCEGUI_CVFSHandleToMyGuiDataStreamAdapter.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

**Comment by LiberatorUSA** [comment]
Hi,

The build system uses auto-generation of CMake and premake files. the automake files are obsolete and should be removed. They are not maintained. I generate the files automatically using ProjectGenerator. bash/batch files for it are in the sub-dirs under /projects

You happened to get the archive at a time when some things got broken and RL matters prevented me from spending any time to fix it. 
Most of the CMake warnings you can ignore, they do not apply as the main CMake file was retro-fitted from the Ogre3D project. The only one that mattered was the 
guidriverCEGUI related one, which should be resolved now.
